=== victorroblesgarcia/tecnologiasweb/p12/spotify_ns.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:tw="http://tecnologiasweb.com.mx"
    targetNamespace="http://tecnologiasweb.com.mx" elementFormDefault="unqualified" attributeFormDefault="unqualified">
    
    <xsd:element name="nombre" type="xsd:string"/>
    <xsd:element name="correo" type="xsd:string"/>
    <xsd:element name="telefono">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:string">
                    <xsd:attribute name="tipo" type="xsd:string" use="required"/>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:complexType name="cuentaType">
        <xsd:sequence>
            <xsd:element ref="tw:nombre"/>
            <xsd:element ref="tw:correo"/>
            <xsd:element ref="tw:telefono" minOccurs="0"/> 
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="plan" type="xsd:string" use="required"/>
        <xsd:attribute name="fechaIni" type="xsd:string" use="optional"/>
        <xsd:attribute name="fechaFin" type="xsd:string" use="optional"/>
    </xsd:complexType>
    
    <xsd:element name="Cuenta" type="tw:cuentaType"/>
    
    <xsd:complexType name="spotifyType">
        <xsd:sequence>
            <xsd:element ref="tw:Cuenta" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="version"/>
    </xsd:complexType>
    
    <xsd:element name="Spotify" type="tw:spotifyType"/>
</xsd:schema>

=== victorroblesgarcia/tecnologiasweb/p12/spotify_ns.xml
<?xml version="1.0" encoding="UTF-8"?>
<tw:Spotify xmlns:tw="http://tecnologiasweb.com.mx"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://tecnologiasweb.com.mx spotify_ns.xsd" 
    version="1.0">
    <tw:Cuenta id="001" plan="Free">
        <tw:nombre>John Wick</tw:nombre>
        <tw:correo>john011@gmail.com</tw:correo>
        <tw:telefono tipo="movil">000 123 4567</tw:telefono>
    </tw:Cuenta>
    <tw:Cuenta id="002" plan="Familiar" fechaIni="2022-03-01" fechaFin="2023-03-01">
        <tw:nombre>Trinity</tw:nombre>
        <tw:correo>trinity007@gmail.com</tw:correo>
    </tw:Cuenta>
</tw:Spotify>
